from . import marchio_repository
from . import modello_repository
from . import allestimento_repository
from . import motorizzazione_repository
from . import catalogo_repository
from . import optional_repository
from . import configurazione_repository
from . import preventivo_repository
from . import ruolo_repository
from . import utente_repository